## Using Dynamic Programming

In [1]:
import numpy as np

In [2]:
A = [[1, 8, 9, 2],
    [7, 6, -1, 5],
    [5, 5, 6, 3],
    [2, 4, 5, 6],
    [1, -1, 2, 5]]

B = [[1, 8, 8, 6, 4, 1],
    [7, 6, 2, 3, 4, 6],
    [5, 5, 4, 3, -1, 4],
    [1, 3, -4, 4, 7, 6]]

C = [[1, 8],
    [7, 6],
    [5, 5],
    [2, 4],
    [1, 2],
    [2, 5]]

D = [[1, 8, 8, 1, 5, 6, -1],
    [7, 6, 1, 2, 3, -2, 1]]

In [3]:
AllMat = [A, B, C, D]

In [4]:
noOfMatrix = 4
costs = np.zeros((noOfMatrix+1, noOfMatrix+1))
noOfk = np.zeros((noOfMatrix+1, noOfMatrix+1), dtype = int)
dim = [len(AllMat[0]), len(AllMat[1]), len(AllMat[2]), len(AllMat[3]), len(AllMat[3][0])]

In [5]:
dim

[5, 4, 6, 2, 7]

In [6]:
for diff in range(1, noOfMatrix):
    for i in range(1, noOfMatrix - diff + 1):
        input()
        j = i + diff
        min = 1e10
        temp = []
        for k in range(i, j):
            tmp = costs[i][k] + costs[k+1][j] + dim[i-1]*dim[k]*dim[j]
            temp.append(tmp)
            if tmp < min:
                min = tmp
                noOfk[i][j] = k
        costs[i][j] = min
        print(temp)
        print("----------------------------")
        print(costs)
        print("****************************")

[120.0]
----------------------------
[[  0.   0.   0.   0.   0.]
 [  0.   0. 120.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
****************************


[48.0]
----------------------------
[[  0.   0.   0.   0.   0.]
 [  0.   0. 120.   0.   0.]
 [  0.   0.   0.  48.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
****************************


[84.0]
----------------------------
[[  0.   0.   0.   0.   0.]
 [  0.   0. 120.   0.   0.]
 [  0.   0.   0.  48.   0.]
 [  0.   0.   0.   0.  84.]
 [  0.   0.   0.   0.   0.]]
****************************


[88.0, 180.0]
----------------------------
[[  0.   0.   0.   0.   0.]
 [  0.   0. 120.  88.   0.]
 [  0.   0.   0.  48.   0.]
 [  0.   0.   0.   0.  84.]
 [  0.   0.   0.   0.   0.]]
****************************


[252.0, 104.0]
----------------------------
[[  0.   0.   0.   0.   0.]
 [  0.   0. 120.  88.   0.]
 [  0.   0.   0.  48. 104.]
 [  0.   0.   0.   0.  84.]
 [  0.   0.   0.   0.   0.]]
****************************


[244.0, 414.0, 158.0]
----------------------------
[[  0.   0.   0.   0.   0.]
 [  0.   0. 120.  88. 158.]
 [  0.   0.   0.  48. 104.]
 [  0.   0.   0.   0.  84.]
 [  0.   0.   0.   0.   0.]]
****************************


In [7]:
costs

array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   0., 120.,  88., 158.],
       [  0.,   0.,   0.,  48., 104.],
       [  0.,   0.,   0.,   0.,  84.],
       [  0.,   0.,   0.,   0.,   0.]])

In [8]:
noOfk

array([[0, 0, 0, 0, 0],
       [0, 0, 1, 1, 3],
       [0, 0, 0, 2, 3],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0]])

In [9]:
def mulArray(a1, a2):
    arr1 = np.array(a1)
    arr2 = np.array(a2)
    arrResult = np.zeros((arr1.shape[0], arr2.shape[1]))
    for i in range(arrResult.shape[0]):
        for j in range(arrResult.shape[1]):
            for k in range(arr1.shape[1]):
                arrResult[i][j] += arr1[i][k] * arr2[k][j]
    return arrResult

In [10]:
def ChainMatMul(listOfMat, k, i, j):
    if i < j:
        left = ChainMatMul(listOfMat, k, i, k[i][j]) 
        right = ChainMatMul(listOfMat, k, k[i][j]+1, j)
  
        return mulArray(left, right)
    else:
        return listOfMat[i-1]

In [11]:
ChainMatMul(AllMat, noOfk, 1, noOfMatrix)

array([[19405., 27190., 14385.,  6600., 15073.,  3746.,  1083.],
       [15734., 23222., 12957.,  5469., 12974.,  4072.,   690.],
       [17906., 26098., 14383.,  6191., 14554.,  4344.,   838.],
       [14183., 19964., 10614.,  4833., 11075.,  2818.,   777.],
       [ 4182.,  5906.,  3151.,  1427.,  3278.,   848.,   226.]])

In [12]:
mulArray(mulArray(mulArray(A, B), C), D)

array([[19405., 27190., 14385.,  6600., 15073.,  3746.,  1083.],
       [15734., 23222., 12957.,  5469., 12974.,  4072.,   690.],
       [17906., 26098., 14383.,  6191., 14554.,  4344.,   838.],
       [14183., 19964., 10614.,  4833., 11075.,  2818.,   777.],
       [ 4182.,  5906.,  3151.,  1427.,  3278.,   848.,   226.]])

In [13]:
def ChainMatMulPrant(listOfMat, k, i, j):
    if i < j:
        left = ChainMatMulPrant(listOfMat, k, i, k[i][j]) 
        right = ChainMatMulPrant(listOfMat, k, k[i][j]+1, j)
  
        print("(" + str(left) +","+ str(right) + ")")
        print("--------------------")
        return "(" + left +","+ right + ")"
    else:
        return listOfMat[i-1]

In [14]:
lis = ["A", "B", "C", "D"]

In [15]:
ChainMatMulPrant(lis, noOfk, 1, 4)

(B,C)
--------------------
(A,(B,C))
--------------------
((A,(B,C)),D)
--------------------


'((A,(B,C)),D)'